### ISSUE TITLE
mxnet.base.MXNetError: value 0 for Parameter num_args should be greater equal to 1, in operator Concat(name="", num_args="0", dim="0")

### ISSUE THREAD

**Issue by cg3575** [Angzz/panoptic-fpn-gluon#5]
Traceback (most recent call last):
  File "train_panoptic_fpn.py", line 562, in <module>
    train(net, train_data, val_data, eval_metric, ctx, args)
  File "train_panoptic_fpn.py", line 440, in train
    for i, batch in enumerate(train_data):
  File "/export/anaconda3/envs/Panoptic-FPN/lib/python3.5/site-packages/mxnet/gluon/data/dataloader.py", line 443, in __next__
    batch = pickle.loads(ret.get()) if self._dataset is None else ret.get()
  File "/export/anaconda3/envs/Panoptic-FPN/lib/python3.5/multiprocessing/pool.py", line 644, in get
    raise self._value
mxnet.base.MXNetError: value 0 for Parameter num_args should be greater equal to 1, in operator Concat(name="", num_args="0", dim="0")

when I train panoptic_fpn , the above problem happened, I don't know how to solve it.

**Comment by Sonaliam** [comment]
I am also facing the same issue after completion of one epoch it throws this error. Please help to solve above issue.

- Thanks
